### ISSUE TITLE
Question about using message broker

### ISSUE THREAD

**Issue by thangchung** [pekkah/tanka-graphql#83]
Hi @pekkah. I really appreciate this project because it helps me a lot for the idea to make GraphQL.NET works with SignalR. I'm refactoring to try this project, but could you please help to explain a bit about how it works if we use some of the message brokers out there such as RabbitMQ or Kafka? I think I will interfere with [`BroadcastBlock`](https://github.com/pekkah/tanka-graphql/blob/master/samples/graphql.samples.chat.data/IChat.cs#L29), right? And how it can subscribe after we publish an event from other publishers?

**Comment by pekkah** [comment]
If you look at `SubscribeToChannel` in the sample https://github.com/pekkah/tanka-graphql-samples/blob/master/src/Host.Logic/Schemas/ChatResolvers.cs and create similar subscriber which would in case of Kafka create a consumer similar to "Basic Consumer Example" at https://github.com/confluentinc/confluent-kafka-dotnet and instead of just writing the message to console you write it to target buffer block. Just remember to also write the error to the block in case of error occurs. Similar approach should work also for RabbitMQ. 

If you want to actually use Kafka or RabbitMQ as an transport for the query data then you need to either find a SignalR transport for the protocol or implement it your self.

**Comment by thangchung** [comment]
@pekkah Thank you very much for your detail explanation 👍
